### ISSUE TITLE
What's going on with this?

### ISSUE THREAD

**Issue by oxr463** [shadow-maint/shadow-www#1]
It doesn't seem like there is currently a website.

**Comment by hallyn** [comment]
There isn't :)  Patches welcome!

**Comment by oxr463** [comment]
> There isn't :) Patches welcome!

Could it be hosted on GitHub Pages? If so, then I can replace the PHP with HTML. Or, we can start from scratch with a static site generator?

**Comment by hallyn** [comment]
I think github pages was my original intent.  Static site generator sounds great.

**Comment by oxr463** [comment]
> I think github pages was my original intent. Static site generator sounds great.

Let me put together a PR.

**Comment by oxr463** [comment]
@hallyn please pull my gh-pages branch, (See: https://github.com/oxr463/shadow-www/tree/gh-pages). This should automatically deploy to GitHub Pages. You can see how it looks here, https://oxr463.github.io/shadow-www. At this point, it's just like the original site.

**Comment by hallyn** [comment]
Thank you!  I'm sorry I've not yet had time to look at it.  Things should slow down middle of this week or early next.  I took a first look this weekend and it looked great, thanks.

**Comment by oxr463** [comment]
@hallyn any updates on this?

**Comment by hallyn** [comment]
Sorry, could you do a PR from your branch?

**Comment by oxr463** [comment]
> Sorry, could you do a PR from your branch?

It won't let me create a PR for a branch that doesn't exist at the source:

![image](https://user-images.githubusercontent.com/43783393/140332566-9a742457-ea41-40d5-8dc2-fcba064a48db.png)

Can you create a new `gh-pages` branch off of master for me to push to?

**Comment by hallyn** [comment]
Sorry, what's the problem?  It's defaulting to master, that's what you want to push to, right?  It *looks* like the 'Create pull request" button there should just work?

If you like, I can fetch your three commits and push them.

**Comment by oxr463** [comment]
> Sorry, what's the problem? It's defaulting to master, that's what you want to push to, right? It _looks_ like the 'Create pull request" button there should just work?
> 
> If you like, I can fetch your three commits and push them.

Because it's using GitHub Pages, we need to use a `gh-pages` branch.

**Comment by hallyn** [comment]
Ok, done.

**Comment by oxr463** [comment]
Here is the current site URL: https://shadow-maint.github.io/shadow-www
