### ISSUE TITLE
[Proposal] Close this project and the web page

### ISSUE THREAD

**Issue by ikerexxe** [shadow-maint/shadow-www#4]
As https://github.com/shadow-maint/shadow/pull/693 has already been merged all the relevant information for the shadow project is autocontained in the development repository so I'd like to propose to close this project and the web page.

The main reason for closing is that we don't have enough time to maintain this project up to date and spreading ourselves isn't helping to focus on the most relevant topic: having a quality [shadow](https://github.com/shadow-maint/shadow) project. As mentioned in https://github.com/shadow-maint/shadow/pull/693, the shadow project has two type of consumers: developers and sysadmins. The former will expect to have all the meaningful documentation (development guidelines, release notes, etc.) in the development repository. The latter is interested in how to configure and use the commands, which can be checked in the man pages, and in the release notes, which are already up-to-date [here](https://github.com/shadow-maint/shadow/releases).

Finally, https://shadow-maint.github.io/shadow-www/ isn't mentioned anywhere in the documentation. So, I don't think many people will be able to find it.

**Comment by hallyn** [comment]
Well, it was really created to archive the historical information.  

How about I hit the 'archive" button, rather than close it?

**Comment by ikerexxe** [comment]
That sounds perfect to me! :smile:
